name: yellow_pass
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  dio: ^5.4.1
  flutter_login: ^5.0.0
  google_nav_bar: ^5.0.6
  permission_handler: ^11.3.1
  firebase_messaging: ^14.7.21
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  firebase_core: ^2.27.2
  go_router: ^13.2.2
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
