// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE1AmQhGiU6uodfFvqEtqKbSocQFPK92o',
    appId: '1:159448260362:web:498dc4f19af9dfe2dde4f3',
    messagingSenderId: '159448260362',
    projectId: 'guadalajara-17336',
    authDomain: 'guadalajara-17336.firebaseapp.com',
    storageBucket: 'guadalajara-17336.appspot.com',
    measurementId: 'G-M16ZLC97WW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpETqx1aI70oclYcWAXhznubTM0sAj_tk',
    appId: '1:159448260362:android:3a0fa7282e9bdf84dde4f3',
    messagingSenderId: '159448260362',
    projectId: 'guadalajara-17336',
    storageBucket: 'guadalajara-17336.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjfjHSGLABKo5ZxXQPoYDfoIAFVdg828Q',
    appId: '1:159448260362:ios:a83bbb3954184a3adde4f3',
    messagingSenderId: '159448260362',
    projectId: 'guadalajara-17336',
    storageBucket: 'guadalajara-17336.appspot.com',
    iosBundleId: 'com.example.yellowPass',
  );
}
